setup:
  build: ./setup
  volume_driver: local
  volumes:
    - mailsettings:/mail_settings

core:
  build: ./core
  ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
  volume_driver: local
  volumes:
    - mailsettings:/mail_settings
    - maildata:/vmail
  links:
   - opendkim
   - amavis

opendkim:
  build: ./opendkim
  volume_driver: local
  volumes:
    - mailsettings:/mail_settings

amavis:
  build: ./amavis
  volume_driver: local
  volumes:
    - mailsettings:/mail_settings
