#!/bin/bash

domain=$1

if [ -z "$domain" ]; then
  echo "Usage: $(basename ${0}) <domain>"
  exit 1
fi

echo "Generating keys for $domain"

opendkim-genkey -d "$domain"

echo "Add a TXT domain record with key: \"default._domainkey\" and value:"

echo "---------"
echo $(cat default.txt | cut -d "(" -f2 | cut -d ")" -f1 | sed 's/[[:space:]]*//' | sed ':a;N;$!ba;s/\n//g' | sed 's/\"//g')
echo "---------"

rm default.txt

echo "Saving private key to: /mail_settings/$domain.opendkim_key";
cat default.private > "/mail_settings/$domain.opendkim_key"

rm default.private
